# Levantar este stack:
# docker compose -f docker-compose.linux.yml up -d --force-recreate

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonar_net

  app:
    # image: richardcollao/sonar-app:1.0.1
    build:
      # context: Define la ruta raíz desde donde Docker busca archivos para COPY en el Dockerfile
      context: /home/richard/www            # ruta absoluta válida en Linux
      dockerfile: DockerProjects/SonarProject/Dockerfile # ruta relativa al build context
    container_name: sonar_app
    depends_on:
      - sonarqube
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Necesario para que el explorador de archivos (BASE_DIR=/workspace)
      # pueda listar carpetas del host sin devolver HTTP 500.
      - /home/richard/www:/workspace
    networks:
      - sonar_net

networks:
  sonar_net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
