# Levantar este stack:
# docker compose -f docker-compose.windows.yml up -d --force-recreate

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonar_net

  app:
    image: richardcollao/sonar-app:1.0.0
    container_name: sonar_app
    depends_on:
      - sonarqube
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
    # Importante: Reemplazar C:/Users/Richard/www por la ruta local donde tiene sus proyectos antes de iniciar el contenedor.
      - "C:/Users/Richard/www:/workspace"
    networks:
      - sonar_net

networks:
  sonar_net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
